# 
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '1':
        frame_id: /observer
        pose2d: /observer/ground_pose
    '2':
        frame_id: /picket_1
    '3':
        frame_id: /picket_2
